"use client";

import { useEffect, useMemo, useState } from "react";
import { evaluateRecovery, executeRecovery, getDisruptions, getHealth, getImpact, getOrders, getRecoveryPlans, getVehicles, type Disruption, type Evaluation, type ExecutionResult, type Impact, type Recovery, type RecoveryPlan, type Vehicle } from "@/lib/api";

const disruptionId = "D001";
const money = (amount: number) => `\u20B9${amount.toLocaleString("en-IN")}`;
const planName = (plan: RecoveryPlan) => plan.type.replaceAll("_", " ").toLowerCase().replace(/\b\w/g, (letter) => letter.toUpperCase());
const ago = (value: string) => { const time = new Date(value).getTime(); return Number.isNaN(time) ? "Timestamp unavailable" : `Detected ${Math.max(0, Math.floor((Date.now() - time) / 60000))} min ago`; };

export default function Page() {
  const [impact, setImpact] = useState<Impact>(); const [recovery, setRecovery] = useState<Recovery>(); const [evaluation, setEvaluation] = useState<Evaluation>();
  const [vehicles, setVehicles] = useState<Vehicle[]>([]); const [disruption, setDisruption] = useState<Disruption>(); const [selectedId, setSelectedId] = useState<string>();
  const [execution, setExecution] = useState<ExecutionResult>(); const [loading, setLoading] = useState(true); const [executing, setExecuting] = useState(false); const [error, setError] = useState<string>();
  async function load() {
    setLoading(true); setError(undefined);
    try {
      const [health, fleet, , disruptions, impactResult, recoveryResult, evaluationResult] = await Promise.all([getHealth(), getVehicles(), getOrders(), getDisruptions(), getImpact(disruptionId), getRecoveryPlans(disruptionId), evaluateRecovery(disruptionId)]);
      if (health.status !== "healthy") throw new Error("RouteGuard API health check failed.");
      setVehicles(fleet); setImpact(impactResult); setRecovery(recoveryResult); setEvaluation(evaluationResult); setDisruption(disruptions.find((item) => item.disruption_id === disruptionId) ?? impactResult.disruption); setSelectedId((current) => current ?? evaluationResult.recommended_plan);
    } catch (cause) { setError(cause instanceof Error ? cause.message : "Backend unavailable. Check that RouteGuard API is running."); }
    finally { setLoading(false); }
  }
  useEffect(() => { void load(); }, []);
  const plans = useMemo(() => recovery?.recovery_plans.map((plan) => ({ ...plan, evaluator_score: evaluation?.plans.find((item) => item.plan_id === plan.plan_id)?.evaluator_score })) ?? [], [recovery, evaluation]);
  const selected = plans.find((plan) => plan.plan_id === selectedId); const recommended = plans.find((plan) => plan.plan_id === evaluation?.recommended_plan); const executed = execution?.status === "EXECUTED";
  const selectedVehicles = selected?.vehicles.map((id) => vehicles.find((vehicle) => vehicle.vehicle_id === id)).filter((vehicle): vehicle is Vehicle => Boolean(vehicle)) ?? [];
  async function execute() { if (!selected || executing || executed) return; setExecuting(true); setError(undefined); try { setExecution(await executeRecovery(disruptionId, selected.plan_id)); } catch (cause) { setError(cause instanceof Error ? cause.message : "Recovery execution failed."); } finally { setExecuting(false); } }
  if (loading) return <main className="grid min-h-screen place-items-center bg-slate-50 font-semibold text-slate-600">Loading live operational data...</main>;
  if (!impact || !recovery || !evaluation || !disruption) return <main className="grid min-h-screen place-items-center bg-slate-50 p-6 text-center"><div><p className="font-bold text-red-700">{error ?? "No active disruptions."}</p><button onClick={() => void load()} className="mt-4 rounded-xl bg-blue-600 px-4 py-2 font-bold text-white">Retry connection</button></div></main>;
  const stages = [["Detection", "complete", `${disruption.type.replaceAll("_", " ")} confirmed`], ["Impact Analysis", "complete", `${impact.affected_orders} affected orders`], ["Recovery Planning", "complete", `${plans.length} plans generated`], ["Evaluation", "complete", `${evaluation.recommended_plan} recommended`], ["Human Approval", executed ? "complete" : "pending", executed ? "Approved" : "Awaiting operator"], ["Execution", executed ? "complete" : "pending", executed ? execution.message : "Pending approval"]] as const;
  const events = [[`${disruption.vehicle_id} disruption detected`, disruption.location, disruption.timestamp], ["Impact analyzed", `${impact.affected_orders} orders · ${impact.sla_risk.critical} critical · ${money(impact.cod_exposure)} COD`, disruption.timestamp], ["Recovery plans generated", `${plans.length} deterministic options`, disruption.timestamp], ["Recommendation generated", `${evaluation.recommended_plan}: ${evaluation.reason}`, disruption.timestamp], [executed ? "Recovery execution completed" : "Human approval pending", executed ? execution.message : "Select a plan and approve execution.", executed ? new Date().toISOString() : disruption.timestamp]];
  return <main className="min-h-screen bg-[#f5f7fb] text-slate-900"><header className="border-b border-slate-200 bg-white"><div className="mx-auto flex max-w-[1500px] items-center justify-between px-5 py-5 sm:px-8"><div><h1 className="text-xl font-black text-blue-600">RouteGuard AI</h1><p className="text-xs font-bold uppercase tracking-widest text-slate-400">Autonomous recovery control tower</p></div><span className="rounded-full bg-emerald-50 px-3 py-2 text-xs font-bold text-emerald-700">API connected</span></div></header><div className="mx-auto max-w-[1500px] p-5 sm:p-8">
    {error && <div role="alert" className="mb-5 rounded-xl border border-red-200 bg-red-50 p-4 text-sm font-semibold text-red-700">{error}</div>}
    <section className="mb-6 rounded-3xl border border-red-200 bg-red-50 p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><b className="text-sm text-red-800">ACTIVE DISRUPTION · {disruption.disruption_id}</b><p className="text-sm text-red-700">{disruption.type.replaceAll("_", " ")} · {disruption.vehicle_id} · {disruption.location}</p></div><p className="text-sm font-semibold text-red-700">{ago(disruption.timestamp)} · {impact.affected_orders} orders affected</p></div></section>
    <section className="mb-6 grid gap-5 lg:grid-cols-[1.45fr_.8fr]"><div className="rounded-3xl bg-white p-7 shadow-sm"><p className="text-xs font-bold uppercase tracking-widest text-red-600">Recovery in progress</p><h2 className="mt-3 text-3xl font-black">{disruption.vehicle_id} requires recovery.</h2><p className="mt-3 text-slate-600">Operational data is sourced from the RouteGuard backend.</p><div className="mt-6 grid grid-cols-2 gap-3 sm:grid-cols-4"><Metric label="Affected" value={`${impact.affected_orders} orders`} /><Metric label="Critical SLA" value={`${impact.sla_risk.critical}`} /><Metric label="VIP customers" value={`${impact.vip_customers}`} /><Metric label="COD exposure" value={money(impact.cod_exposure)} /></div></div><div className="rounded-3xl bg-white p-6 shadow-sm"><p className="text-sm font-bold text-slate-500">Recovery decision</p><p className="mt-3 text-2xl font-black">{evaluation.recommended_plan}</p><p className="mt-1 text-sm text-slate-600">{evaluation.reason}</p><p className="mt-3 text-lg font-black text-blue-700">{recommended?.evaluator_score?.toFixed(2) ?? "N/A"} / 100</p><button disabled={!selected || executing || executed} onClick={() => void execute()} className="mt-5 w-full rounded-2xl bg-blue-600 px-4 py-3 font-bold text-white disabled:cursor-not-allowed disabled:bg-slate-300">{executed ? "Executed" : executing ? "Executing…" : "Approve & Execute"}</button><p className="mt-3 text-center text-xs text-slate-500">{executed ? `${execution.plan_id} · ${execution.message}` : "Human approval required before execution"}</p></div></section>
    <section className="mb-6 rounded-3xl bg-white p-6 shadow-sm"><div className="flex justify-between gap-4"><div><h2 className="text-xl font-black">Recovery options</h2><p className="text-sm text-slate-500">Choose a backend-generated plan.</p></div><b className="text-sm text-slate-500">{plans.length} plans generated</b></div><div className="mt-5 grid gap-4 md:grid-cols-3">{plans.map((plan) => <button key={plan.plan_id} disabled={executed} onClick={() => setSelectedId(plan.plan_id)} className={`rounded-2xl border p-5 text-left disabled:cursor-not-allowed ${selectedId === plan.plan_id ? "border-blue-500 bg-blue-50" : "border-slate-200"}`}><div className="flex justify-between gap-2"><b>{plan.plan_id}</b>{plan.plan_id === evaluation.recommended_plan && <span className="text-xs font-bold text-blue-700">RECOMMENDED</span>}</div><p className="mt-2 text-sm text-slate-600">{planName(plan)}</p><p className="mt-1 text-sm text-slate-500">{plan.description}</p><div className="mt-4 grid grid-cols-2 gap-2 text-sm"><b>{money(plan.cost)}</b><b>+{plan.delay_minutes} min</b><span>{plan.sla_saved} SLA saved</span><span>{plan.evaluator_score?.toFixed(2) ?? "N/A"} score</span></div></button>)}</div></section>
    {selected && <section className="mb-6 grid gap-5 lg:grid-cols-2"><div className="rounded-3xl bg-white p-6 shadow-sm"><h2 className="text-xl font-black">Selected plan: {selected.plan_id}</h2><dl className="mt-4 grid grid-cols-2 gap-4 text-sm"><Data label="Cost" value={money(selected.cost)} /><Data label="Expected delay" value={`${selected.delay_minutes} min`} /><Data label="SLA saved" value={`${selected.sla_saved} orders`} /><Data label="Evaluator score" value={selected.evaluator_score?.toFixed(2) ?? "N/A"} /></dl></div><div className="rounded-3xl bg-white p-6 shadow-sm"><h2 className="text-xl font-black">Operational visualization</h2><p className="mt-2 text-sm text-slate-500">Disruption: {disruption.location} · Vehicle: {disruption.vehicle_id}</p><div className="mt-4 flex flex-wrap gap-3">{selectedVehicles.length ? selectedVehicles.map((vehicle) => <span key={vehicle.vehicle_id} className="rounded-xl bg-blue-50 px-3 py-2 text-sm font-bold text-blue-800">{vehicle.vehicle_id} · {vehicle.location} · capacity {vehicle.capacity}</span>) : <span className="text-sm text-slate-500">No replacement vehicles assigned for this plan.</span>}</div></div></section>}
    <section className="mb-6 rounded-3xl bg-white p-6 shadow-sm"><h2 className="text-xl font-black">Autonomous recovery pipeline</h2><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{stages.map(([name, state, detail]) => <div key={name} className="rounded-2xl border border-slate-200 p-4"><div className="flex justify-between gap-2"><b>{name}</b><span className={`rounded-full px-2 py-1 text-xs font-bold ${state === "complete" ? "bg-emerald-50 text-emerald-700" : "bg-amber-50 text-amber-700"}`}>{state}</span></div><p className="mt-2 text-sm text-slate-500">{detail}</p></div>)}</div></section>
    <section className="grid gap-6 lg:grid-cols-[1.6fr_.75fr]"><div className="overflow-hidden rounded-3xl bg-white shadow-sm"><div className="border-b border-slate-100 p-6"><h2 className="text-xl font-black">Orders requiring attention</h2><p className="text-sm text-slate-500">{impact.orders.length} affected orders from impact analysis</p></div><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr>{["Order", "Customer", "Location", "SLA", "Value", "Payment", "Risk"].map((header) => <th key={header} className="px-5 py-3">{header}</th>)}</tr></thead><tbody>{impact.orders.map((order) => <tr key={order.order_id} className="border-t border-slate-100"><td className="px-5 py-4 font-bold">{order.order_id}</td><td className="px-5 py-4">{order.customer_name ?? "Not available"}{order.customer_tier === "VIP" && <span className="ml-2 text-xs font-bold text-amber-600">VIP</span>}</td><td className="px-5 py-4">{order.location}</td><td className="px-5 py-4">{order.sla_deadline}</td><td className="px-5 py-4">{money(order.order_value)}</td><td className="px-5 py-4">{order.payment_type}</td><td className="px-5 py-4 font-bold">{order.priority}</td></tr>)}</tbody></table></div>{impact.orders.length === 0 && <p className="p-6 text-slate-500">No affected orders.</p>}</div><div className="rounded-3xl bg-white p-6 shadow-sm"><h2 className="text-xl font-black">Incident activity</h2><div className="mt-5 space-y-5">{events.map(([title, detail, time]) => <div key={title}><b>{title}</b><p className="mt-1 text-sm text-slate-500">{detail}</p><p className="mt-1 text-xs text-slate-400">{new Date(time).toLocaleString()}</p></div>)}</div></div></section>
  </div></main>;
}
function Metric({ label, value }: { label: string; value: string }) { return <div className="rounded-xl bg-slate-50 p-3"><p className="text-xs font-bold uppercase text-slate-400">{label}</p><p className="mt-1 font-black">{value}</p></div>; }
function Data({ label, value }: { label: string; value: string }) { return <div><dt className="text-xs font-bold uppercase text-slate-400">{label}</dt><dd className="mt-1 text-lg font-black">{value}</dd></div>; }
